name: Deploy React Best Practices to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your branch is different

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "lalitendra.swamy@g7cr.com"
          git config --global user.name "g7crservice-lalitendra-swamy"

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          CI: false
        run: npm run deploy
