name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "lalitendra.swamy@g7cr.com"
          git config --global user.name "g7crservice-lalitendra-swamy"

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh-pages -d build --repo https://GH_TOKEN@github.com/g7crservice-lalitendra-swamy/react-bp.git
